# Generated by Django 3.0.4 on 2020-03-20 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('Android', 'ANDROID'), ('iOS', 'IOS')], max_length=50)),
                ('owner', models.CharField(choices=[('Personal', 'PERSONAL'), ('Empresa', 'EMPRESA')], max_length=50)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
    ]
