# Generated by Django 3.0.4 on 2020-03-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='os_family',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='os_version',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
