# Generated by Django 3.0.4 on 2020-04-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_auto_20200326_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='tlf',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
