# Generated by Django 3.0.4 on 2020-04-27 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_device_tlf'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='onesignal_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
