# Generated by Django 3.0.4 on 2020-03-09 22:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 9, 22, 11, 4, 207154, tzinfo=utc)),
        ),
    ]
