# Generated by Django 3.0.4 on 2020-04-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualnotification',
            name='info',
            field=models.CharField(max_length=350, null=True),
        ),
    ]
