# Generated by Django 3.0.4 on 2020-03-09 22:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20200309_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 9, 22, 20, 27, 882526, tzinfo=utc)),
        ),
    ]
