# Generated by Django 3.0.4 on 2020-03-22 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
        ('notification', '0003_auto_20200323_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualnotification',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device', to='device.Device'),
        ),
    ]
