# Generated by Django 3.0.4 on 2020-03-09 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_auto_20200309_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
