# Generated by Django 3.0.4 on 2020-03-23 08:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_auto_20200323_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualnotification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='individualnotification',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
