"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 2.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""
from ._secrets import *
from ._vars import *
import environ
import os
import sys

env = environ.Env()
ROOT_DIR = environ.Path(__file__) - 3
APPS_DIR = ROOT_DIR.path('validator_notification')

READ_DOT_ENV_FILE = env.bool('DJANGO_READ_DOT_ENV_FILE', default=False)
VAL_NOT_ENV = env.str('NT_ENV', default='local')

if READ_DOT_ENV_FILE:
    print(f'\U0001F40D *** Loading environment: {VAL_NOT_ENV} *** \U0001F40D')
    env_files = ['.vars', '.secrets']
    env_files_paths = [str(ROOT_DIR.path(f'.envs/{VAL_NOT_ENV}/{env_file}')) for env_file in env_files]
    for env_file_path in env_files_paths:
        if os.path.isfile(env_file_path):
            env.read_env(env_file_path)
        else:
            print(f'*** \U0001F525 Warning: missing env file: {env_file_path}\n', file=sys.stderr)


TIME_ZONE = 'Europe/Madrid'
LANGUAGE_CODE = 'es-es'
SITE_ID = 1
USE_I18N = True
USE_L10N = True
USE_TZ = True

LANGUAGES = (
    ('es', 'Spanish'),
    ('en', 'English'),
    ('pt', 'Portugues'),
    ('ca', 'Catalan'),
    ('eu', 'Euskera'),
    ('gl', 'Gallego'),
    ('va', 'Valenciano'),
)

LOCALE_PATHS = (
    os.path.join(APPS_DIR, 'locale'),
)

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ROOT_URLCONF = 'config.urls'
WSGI_APPLICATION = 'config.wsgi.application'
STATIC_URL = '/static/'


ALLOWED_HOSTS = []


DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'corsheaders',
    'rest_framework',
    'knox'
]
THIRD_PARTY_APPS = []
LOCAL_APPS = [
    'validator_notification.apps.device',
    'validator_notification.apps.user',
    'validator_notification.frontend',
    'validator_notification.apps.accounts'
]

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': ('knox.auth.TokenAuthentication',)
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'corsheaders.middleware.CorsPostCsrfMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

LANGUAGE_DEFAULT = {
    'language_code': 'es',
    'language_country': 'ES',
    'language_name': 'Español'
}
LANGUAGES_AVAILABLE = ['es', 'ca', 'gl', 'eu', 'en', 'pt', 'va']
