export const GET_DEVICES = "GET_DEVICES";
export const DELETE_DEVICE = "DELETE_DEVICE";
export const ADD_DEVICE = "ADD_DEVICE";
export const CLEAR_DEVICES = "CLEAR_DEVICES";
export const ADD_DEVICE_FAIL = "ADD_DEVICE_FAIL";

export const GET_ERRORS = "GET_ERRORS";

export const CREATE_MESSAGE = "CREATE_MESSAGE";

export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const GET_NOTIFICATION = "GET_NOTIFICATION";
export const UPDATE_NOTIFICATION = "UPDATE_NOTIFICATION";
export const CLEAR_NOTIFICATIONS = "CLEAR_NOTIFICATIONS";

export const ADD_GENERAL_NOTIFICATION = "ADD_GENERAL_NOTIFICATION";
export const ADD_GENERAL_NOTIFICATION_FAIL = "ADD_GENERAL_NOTIFICATION_FAIL";
export const GET_GENERAL_NOTIFICATIONS = "GET_GENERAL_NOTIFICATIONS";
export const GET_GENERAL_NOTIFICATIONS_FAIL = "GET_GENERAL_NOTIFICATIONS_FAIL";
export const DELETE_GENERAL_NOTIFICATION = "DELETE_GENERAL_NOTIFICATION";
export const DELETE_GENERAL_NOTIFICATION_FAIL = "DELETE_GENERAL_NOTIFICATION_FAIL";

export const GET_NOTIFICATIONS_ALL = "GET_NOTIFICATIONS_ALL";
export const GET_INDIVIDUAL_NOTIFICATIONS = "GET_INDIVIDUAL_NOTIFICATIONS";
